-- Sample data inserts. These are just for development.

insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Froi', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Sasha', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Reimen', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Axel', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Barba', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Maksim', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Clara', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Giovanni', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Jose', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');
insert into testimonials(name, town, proud_of, pride_in, youtube_link) values ('Imanol', 'Guaynabo', 'everything and more', 'not enough', 'http://www.youtube.com/embed/VVLSvWLOYtg');

-- Functionality to use this not yet implemented
-- insert into municipios (name) values('Adjuntas');
-- insert into municipios (name) values('Aguada');
-- insert into municipios (name) values('Aguadilla');
-- insert into municipios (name) values('Aguas Buenas');
-- insert into municipios (name) values('Aibonito');
-- insert into municipios (name) values('Añasco');
-- insert into municipios (name) values('Arecibo');
-- insert into municipios (name) values('Arroyo');
-- insert into municipios (name) values('Barceloneta');
-- insert into municipios (name) values('Barranquitas');
-- insert into municipios (name) values('Bayamón');
-- insert into municipios (name) values('Cabo Rojo');
-- insert into municipios (name) values('Caguas');
-- insert into municipios (name) values('Camuy');
-- insert into municipios (name) values('Canóvanas');
-- insert into municipios (name) values('Carolina');
-- insert into municipios (name) values('Cataño');
-- insert into municipios (name) values('Cayey');
-- insert into municipios (name) values('Ceiba');
-- insert into municipios (name) values('Ciales');
-- insert into municipios (name) values('Cidra');
-- insert into municipios (name) values('Coamo');
-- insert into municipios (name) values('Comerío');
-- insert into municipios (name) values('Corozal');
-- insert into municipios (name) values('Culebra');
-- insert into municipios (name) values('Dorado');
-- insert into municipios (name) values('Fajardo');
-- insert into municipios (name) values('Florida');
-- insert into municipios (name) values('Guánica');
-- insert into municipios (name) values('Guayama');
-- insert into municipios (name) values('Guayanilla');
-- insert into municipios (name) values('Guaynabo');
-- insert into municipios (name) values('Gurabo');
-- insert into municipios (name) values('Hatillo');
-- insert into municipios (name) values('Hormigueros');
-- insert into municipios (name) values('Humacao');
-- insert into municipios (name) values('Isabela');
-- insert into municipios (name) values('Jayuya');
-- insert into municipios (name) values('Juana Díaz');
-- insert into municipios (name) values('Juncos');
-- insert into municipios (name) values('Lajas');
-- insert into municipios (name) values('Lares');
-- insert into municipios (name) values('Las Marías');
-- insert into municipios (name) values('Las Piedras');
-- insert into municipios (name) values('Loíza');
-- insert into municipios (name) values('Luquillo');
-- insert into municipios (name) values('Manatí');
-- insert into municipios (name) values('Maricao');
-- insert into municipios (name) values('Maunabo');
-- insert into municipios (name) values('Mayagüez');
-- insert into municipios (name) values('Moca');
-- insert into municipios (name) values('Morovis');
-- insert into municipios (name) values('Naguabo');
-- insert into municipios (name) values('Naranjito');
-- insert into municipios (name) values('Orocovis');
-- insert into municipios (name) values('Patillas');
-- insert into municipios (name) values('Peñuelas');
-- insert into municipios (name) values('Ponce');
-- insert into municipios (name) values('Quebradillas');
-- insert into municipios (name) values('Rincón');
-- insert into municipios (name) values('Río Grande');
-- insert into municipios (name) values('Sabana Grande');
-- insert into municipios (name) values('Salinas');
-- insert into municipios (name) values('San Germán');
-- insert into municipios (name) values('San Juan');
-- insert into municipios (name) values('San Lorenzo');
-- insert into municipios (name) values('San Sebastián');
-- insert into municipios (name) values('Santa Isabel');
-- insert into municipios (name) values('Toa Alta');
-- insert into municipios (name) values('Toa Baja');
-- insert into municipios (name) values('Trujillo Alto');
-- insert into municipios (name) values('Utuado');
-- insert into municipios (name) values('Vega Alta');
-- insert into municipios (name) values('Vega Baja');
-- insert into municipios (name) values('Vieques');
-- insert into municipios (name) values('Villalba');
-- insert into municipios (name) values('Yabucoa');
-- insert into municipios (name) values('Yauco');